### PR TITLE
Issue24

### PR DESCRIPTION
**Pull request by phax**
Simplified common types as requested by #24

### CODE REVIEW

**Comment by phax** [comment]
This branch is based on the USI redirect change branch (#29 ) - so please don't get confused

**Comment by phax** [comment]
Only https://github.com/de4a-wp5/xml-schemas/commit/94415e14d4a43085704e3001e8350195a6dd1f08is relevant

**Comment by phax** [comment]
So - now the changelist ist okay ;-)

**Review by danieldecastrop — APPROVED** [review]
Aproved

**Pull request merged**
